name: Simple CI - Spring PetClinic

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t petclinic-app .

      - name: Start app and database
        run: docker compose -f docker-compose-postgres.yml up -d

      - name: Wait for app
        run: |
          echo "Waiting for app to start..."
          for i in {1..10}; do
            if curl -sf http://localhost:8085 > /dev/null; then
              echo "✅ App is running!"
              exit 0
            fi
            echo "⏳ Waiting... ($i)"
            sleep 10
          done
          echo "❌ App failed to start!"
          exit 1

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose-postgres.yml down -v
