name: CI/CD - Spring Petclinic with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build the Docker image for your Spring app
      - name: Build Petclinic Docker image
        run: |
          echo "Building Docker image..."
          docker build -t petclinic-app .

      # Step 4: Stop and remove any old containers (clean environment)
      - name: Stop old containers
        run: |
          echo "Stopping and removing old containers..."
          docker compose -f docker-compose-postgres.yml down -v || true

      # Step 5: Start new containers (PostgreSQL + Spring App)
      - name: Start containers with docker-compose
        run: |
          echo "Starting containers..."
          docker compose -f docker-compose-postgres.yml up -d
          echo "Containers started successfully!"
          docker ps

      # Step 6: Verify that the app is running
      - name: Check Petclinic health
        run: |
          echo "Waiting for the app to start..."
          sleep 20
          curl -f http://localhost:8080 || (echo "App did not start!" && exit 1)
